### ISSUE TITLE
Cannot convert interleaved phylip files correctly.

### ISSUE THREAD

**Issue by curiosusJR** [agormp/seqconverter#2]
Current procedure cannot handle interleaved phylip files correctly. In particular,  the default output is the width of 60 interleaved phylip format file, but it can not convert it back to the original format.

This is a sample that can reproduce the bug on my computer.

A file
```
>taxa1.1
ATCG
>taxa2.1
ACCG
>taxa3.1
GCGT
```

named 'test.fas'. Run `seqconverter -i test.fas --outformat phylip --width 3 | seqconverter ` 

and get 

> Error: Not an alignment: these sequences have different lengths: G and taxa1.1

If only it could handle interleaved phylip the same way it handles interleaved nexus. 

In addition, I want to be able to output the entire length of the sequence on one line by `--width -1`. 

BEST WISHES!

**Comment by agormp** [comment]
Thanks for pointing this out! The phylip parsing issue should be fixed in the new version 3.1.1, so it should work if you upgrade:

python3 -m pip install --upgrade seqconverter

I will add the width feature later today.

Cheers,
Anders

**Comment by agormp** [comment]
I have now added the width feature also (in version 3.2.0). Can be installed from pypi also:

python3 -m pip install --upgrade seqconverter

The option 
    --width -1 

will print each sequence on a single line.

**Comment by agormp** [comment]
Also updated the help text now. Let me know if something is still not working.

**Comment by curiosusJR** [comment]
Thank you very much for your positive reply. This procedure greatly facilitates the collaboration between programs with different format requirements. 

The output files of some programs are slightly out of standard phylip format, which can seem to cause minor problems. Specifically, sometimes a phylip file will have a blank line at the end, which `seqconverter` will not be able to read. For example, `phylobayes` will output a phylip align without spaces at the beginning of the first line and a blank line at the end when doing predictive simulation.

I know this is not a problem with this procedure, just a casual talk. 

Thank you very much for your reply again, best wishes!

**Comment by agormp** [comment]
I dropped the requirement for spaces at the beginning of the first line in this version so that part should work now. Can you send an example of a phylobayes file that is not working?

**Comment by curiosusJR** [comment]
I have updated to 3.2.1. And I tested a file 
```
3   4
taxa1.1  ATCG
taxa2.1  ACCG
taxa3.1  GCGT
```
with `seqconverter -i test.phy` and get error: 
```
Traceback (most recent call last):
  File "/home/junru/.local/bin/seqconverter", line 8, in <module>
    sys.exit(main())
  File "/home/junru/.local/lib/python3.10/site-packages/seqconverter.py", line 29, in main
    seqs,args = read_seqs(args)
  File "/home/junru/.local/lib/python3.10/site-packages/seqconverter.py", line 382, in read_seqs
    seqfile = sq.Seqfile(filename, args.informat)
  File "/home/junru/.local/lib/python3.10/site-packages/sequencelib.py", line 4019, in __new__
    elif (len(firstline.split()) >= 2) and (firstline.split()[0].isdigit) and firstline[6] == " ":
IndexError: string index out of range
```

if add `--informat phylip` and it will be no error.

And a file 
```
     3   4
taxa1.1  ATCG
taxa2.1  ACCG
taxa3.1  GCGT

```
and run a same command and get error:
```
Traceback (most recent call last):
  File "/home/junru/.local/bin/seqconverter", line 8, in <module>
    sys.exit(main())
  File "/home/junru/.local/lib/python3.10/site-packages/seqconverter.py", line 29, in main
    seqs,args = read_seqs(args)
  File "/home/junru/.local/lib/python3.10/site-packages/seqconverter.py", line 389, in read_seqs
    seqlist.append(seqfile.read_alignment(args.dupnamefilter))
  File "/home/junru/.local/lib/python3.10/site-packages/sequencelib.py", line 3790, in read_alignment
    line = self.seqdata[i]
IndexError: list index out of range
```

This is a output of phylobayes predictive simulation.
```
3	4
taxa1.1     GTCT
taxa2.1     GGTT
taxa3.1     GTGT

```
It is a \<tab\> between 3 and 4.

**Comment by agormp** [comment]
Ah yes - I forgot to update the file-format auto detection code. Your examples seem to work for me now, regardless of whether the last line is blank or not, and regardless of types of white-space. Can you update to 3.2.2 and check that it works for you?

**Comment by curiosusJR** [comment]
I have updated 3.2.2 and tested. The types of white-space and detection goes fine but blank line still makes error.

```
$ echo "3 4\ntaxa1.1 ATCG\ntaxa2.1 ATCC\ntaxa3.1 GCGC" | seqconverter
>taxa1.1
ATCG
>taxa2.1
ATCC
>taxa3.1
GCGC


$ echo "3 4\ntaxa1.1 ATCG\ntaxa2.1 ATCC\ntaxa3.1 GCGC\n" | seqconverter
Traceback (most recent call last):
  File "/home/junru/.local/bin/seqconverter", line 8, in <module>
    sys.exit(main())
  File "/home/junru/.local/lib/python3.10/site-packages/seqconverter.py", line 29, in main
    seqs,args = read_seqs(args)
  File "/home/junru/.local/lib/python3.10/site-packages/seqconverter.py", line 389, in read_seqs
    seqlist.append(seqfile.read_alignment(args.dupnamefilter))
  File "/home/junru/.local/lib/python3.10/site-packages/sequencelib.py", line 3790, in read_alignment
    line = self.seqdata[i]
IndexError: list index out of range
```

**Comment by agormp** [comment]
Found the bug now (trailing blank lines caused phylip parser to expect extra sequence block). Please test if things are working when upgrading to 3.2.3

**Comment by curiosusJR** [comment]
Everything is going well now! Thank you!

**Comment by agormp** [comment]
Excellent! Closing this for now. Feel free to reopen if needed.
